### ISSUE TITLE
Understand perf for marshalling a slice using pool

### ISSUE THREAD

**Issue by sudo-suhas** [go-playground/pool#12]
Hey @joeybloggs, could you please take a look at this and let me know what you think -
 https://github.com/sudo-suhas/bulk-marshal? I don't have enough expertise to decipher the relatively poor performance of this library compared to goroutines with channels and wait groups. Would very much like to know your take on this.

**Comment by deankarn** [comment]
Hey @sudo-suhas 

Thanks for the question. The short of it is that I built this library back when I was still new at Go and the library can definitely be cleaned up and sped up a lot with what I know now.

But honestly I recommend using goroutines as first class citizens like you have done in your parallel tests, they’re easier to reason about and can be strongly typed avoiding a lot of type casting, which of course a library like this can never be(without generics).

I do have plans to clean this library up in the backend, but it’s low on my priority list ATM.

I hope I answered your questions to your satisfaction:) please let me know if you have anymore

**Comment by sudo-suhas** [comment]
Thanks @joeybloggs! As always, your answer is through and very helpful. I do have a couple of thoughts I'd like to share. One reason I had used this library some time back was because the API was much easier for me to understand and implement worker pools. Moreover, with regards to the implementation which used goroutines, I felt it was non-trivial to implement and I wasn't 100% sure I was doing everything right. In any case, I think we can close the issue.
