### ISSUE TITLE
Example don't work

### ISSUE THREAD

**Issue by akamajoris** [go-playground/pool#8]
**"Batch Work" example from readme**
`go get`
`go build`

```
.\main.go:12: undefined: pool.NewLimited
.\main.go:44: cannot use func literal (type func(pool.WorkUnit) (interface {}, error)) as type pool.WorkFunc in return argument
.\main.go:50: wu.IsCancelled undefined (type pool.WorkUnit has no field or method IsCancelled)
```

**Comment by deankarn** [comment]
I updated from v2 to v3 pretty quickly can you confirm that you have v3 downloaded and that you used the gopkg.in address to go get?

`go get gopkg.in/go-playground/pool.v3`

It sounds like either you downloaded v2,  but the example is for v3 or did a go get on the GitHub URL and not the gopkg.in.

**Comment by akamajoris** [comment]
Test with import "gopkg.in/go-playground/pool.v2"

```
.\main.go:12: not enough arguments in call to pool.New
.\main.go:33: cannot call non-function email.Error (type error)
.\main.go:39: cannot call non-function email.Value (type interface {})
.\main.go:44: cannot use func literal (type func(pool.WorkUnit) (interface {}, error)) as type pool.WorkFunc in return argument
.\main.go:50: wu.IsCancelled undefined (type pool.WorkUnit has no field or method IsCancelled)
```

Test with import "gopkg.in/go-playground/pool.v3"

```
.\main.go:12: not enough arguments in call to pool.New
.\main.go:33: cannot call non-function email.Error (type error)
.\main.go:39: cannot call non-function email.Value (type interface {})
.\main.go:44: cannot use func literal (type func(pool.WorkUnit) (interface {}, error)) as type pool.WorkFunc in return argument
.\main.go:50: wu.IsCancelled undefined (type pool.WorkUnit has no field or method IsCancelled)
```

OS: Windows 7 x64
go version

```
go version go1.6 windows/386
```

That example: https://github.com/go-playground/pool/blob/v3/examples/unlimited/batch/main.go

**Comment by deankarn** [comment]
Definitly a different issue now and even in a different file.

The errors are definitly indicating that v2 version of the code is being used. I am wondering if there is not a problem with gopkg.in as my godocs are also pointing to v2 and not v3.

Could you list the files in $GOPATH/src/gopkg.in/go-playground/pool.v3, if limited_pool.go is not listed the wrong version of the code may have been downloaded via gopkg.in

**Comment by deankarn** [comment]
ok it's all fixed now, just run `go get -u gopkg.in/go-playground/pool.v3`

I must have selected the v2 branch when creating the v3 release, its the only thing that makes sense.

sorry for the inconvenience, please try after the update and let me know if it works now :)

**Comment by akamajoris** [comment]
Thank you.
I removed old forlders  then `go get -u gopkg.in/go-playground/pool.v3`
It's all fine now.

**Comment by deankarn** [comment]
Perfect, thanks for reporting!
